version: '3.8'
name: iot-webapp-simulation
services:
  api:
    build: 
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./sensor_data.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - iot-network

  webapp:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - api
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge
